name: Our builder
on:
  workflow_call:
runs:
  using: 'composite'
  steps:
    - name: 'test'
      shell: bash
      env:
        GHA_PATH: ${{ github.action_path }}
      run: |
        echo "Running the builder"
