---
name: Demo
on:
  - pull_request
jobs:
  demo2:
    runs-on: ubuntu-latest
    steps:
    - name: print something2
      run: echo "someting22"
  usetrw:
    uses: ./.github/workflows/trw.yml
    with:
      name1: value1
      name2: value2
      private-repository: false
